# Generated by Django 2.0.1 on 2021-08-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('population', models.IntegerField(default=0)),
                ('total_vaccinated', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('total_rgistered', models.IntegerField(default=0)),
                ('doss_1st_done', models.IntegerField(default=0)),
            ],
        ),
    ]
