# Generated by Django 2.0.1 on 2021-09-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('population', models.IntegerField(default=0)),
                ('total_vaccinated', models.IntegerField(default=0)),
                ('priority', models.FloatField(default=0)),
                ('total_rgistered', models.IntegerField(default=0)),
                ('doss_1st_done', models.IntegerField(default=0)),
                ('available_doss', models.IntegerField(default=0)),
                ('pending_doss', models.IntegerField(default=0)),
                ('total_doss_area', models.IntegerField(default=0)),
                ('number_of_center', models.IntegerField(default=0)),
                ('enability', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='dosses_for_dhaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosses', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
