# Generated by Django 2.0.1 on 2021-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0003_dosses_for_dhaka'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='available_doss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='pending_doss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='total_doss_area',
            field=models.IntegerField(default=0),
        ),
    ]
