# Generated by Django 2.0.1 on 2021-08-19 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
        ('staff', '0002_staff_of_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='center_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('staff_status', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center_name')),
            ],
        ),
        migrations.RemoveField(
            model_name='staff_of_center',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff_of_center',
        ),
    ]
