# Generated by Django 2.0.1 on 2021-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='center_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('available_dosses', models.IntegerField(default=0)),
                ('num_of_dosses', models.IntegerField(default=0)),
                ('updated_time', models.DateField(auto_now_add=True)),
                ('working_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='period_of_dosses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=2)),
                ('target_user', models.IntegerField(default=2)),
                ('num_user', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('center_name', models.ManyToManyField(to='center.center_name')),
            ],
        ),
    ]
