# Generated by Django 2.0.1 on 2021-08-25 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='center_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('updated_dosses', models.IntegerField(default=0)),
                ('available_dosses', models.IntegerField(default=0)),
                ('doss_per_day', models.IntegerField(default=0)),
                ('num_of_dosses', models.IntegerField(default=0)),
                ('updated_time', models.DateField(auto_now_add=True)),
                ('working_time', models.DateField()),
                ('pending_doss_center', models.IntegerField(default=0)),
                ('total_doss_center', models.IntegerField(default=0)),
                ('area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.area')),
            ],
        ),
        migrations.CreateModel(
            name='period_of_dosses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=2)),
                ('target_user', models.IntegerField(default=2)),
                ('num_user', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('second_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('center_name', models.ManyToManyField(to='center.center_name')),
            ],
        ),
    ]
