# Generated by Django 2.0.1 on 2021-08-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center_name',
            name='doss_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
