# Generated by Django 2.0.1 on 2021-08-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_center_name_updated_dosses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period_of_dosses',
            name='date',
            field=models.DateField(),
        ),
    ]
