# Generated by Django 2.0.1 on 2021-08-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=14, unique=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center_name')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.period_of_dosses')),
            ],
        ),
    ]
